apiVersion: v1
kind: Service
metadata:
  name: k8s-deployment-svc
  labels:
    app: k8s_practice
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 8080
  selector:
    app: k8s_practice